<a href="https://colab.research.google.com/github/KarHin22/Practical-Discrete-Mathematics/blob/master/FindNumberOfPath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy

# Create an adjacency matrix for the graph in Figure 8.1
A1 = numpy.array([[0, 1, 1, 0, 1, 0], [1, 0, 1, 1, 0, 1],
                 [1, 1, 0, 1, 1, 0], [0, 1, 1, 0, 1, 0],
                 [1, 0, 1, 1, 0, 0], [0, 1, 0, 0, 0, 0]])

# Create an adjacency matrix for the graph in Figure 8.8
A2 = numpy.array([[0, 1, 0, 0, 0, 0], [1, 0, 0, 0, 0, 1],
                 [0, 0, 0, 1, 1, 0], [0, 0, 1, 0, 1, 0],
                 [0, 0, 1, 1, 0, 0], [0, 1, 0, 0, 0, 0]])

# Create a weight matrix for the network in Figure 8.5
W1 = numpy.array([[0, 4, 1, 0, 2, 0], [4, 0, 2, 1, 0, 1],
                 [1, 2, 0, 1, 1, 0], [0, 1, 1, 0, 2, 0],
                 [2, 0, 1, 2, 0, 0], [0, 1, 0, 0, 0, 0]])

# Create a weight matrix for the directed network in Figure 8.7
W2 = numpy.array([[0, 0, 2, 0, 0, 0], [1, 0, 0, 0, 0, 2],
                 [0, 0, 0, 0, 2, 0], [0, 2, 3, 0, 4, 0],
                 [3, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 1]])

# print the adjacency matrices
print("A1 =", A1)
print("\nA2 =", A2)
print("\nW1 =", W1)
print("\nW2 =", W2)
print("\n")

for counter in range(1,7):
    A1counter = numpy.linalg.matrix_power(A1,counter)
    print("There are", A1counter[0,5], "paths of length", counter, "from v1 to v6")
print("\n")

for counter in range(1,7):
    A2counter = numpy.linalg.matrix_power(A2,counter)
    print("There are", A2counter[0,5], "paths of length", counter, "from v1 to v6")
print("\n")

for counter in range(1,7):
    W1counter = numpy.linalg.matrix_power(W1,counter)
    print("There are", W1counter[0,5], "paths of length", counter, "from v1 to v6")
print("\n")

for counter in range(1,7):
    W2counter = numpy.linalg.matrix_power(W2,counter)
    print("There are", W2counter[0,5], "paths of length", counter, "from v1 to v6")
print("\n")

A1 = [[0 1 1 0 1 0]
 [1 0 1 1 0 1]
 [1 1 0 1 1 0]
 [0 1 1 0 1 0]
 [1 0 1 1 0 0]
 [0 1 0 0 0 0]]

A2 = [[0 1 0 0 0 0]
 [1 0 0 0 0 1]
 [0 0 0 1 1 0]
 [0 0 1 0 1 0]
 [0 0 1 1 0 0]
 [0 1 0 0 0 0]]

W1 = [[0 4 1 0 2 0]
 [4 0 2 1 0 1]
 [1 2 0 1 1 0]
 [0 1 1 0 2 0]
 [2 0 1 2 0 0]
 [0 1 0 0 0 0]]

W2 = [[0 0 2 0 0 0]
 [1 0 0 0 0 2]
 [0 0 0 0 2 0]
 [0 2 3 0 4 0]
 [3 0 1 1 0 0]
 [0 0 0 0 0 1]]


There are 0 paths of length 1 from v1 to v6
There are 1 paths of length 2 from v1 to v6
There are 1 paths of length 3 from v1 to v6
There are 9 paths of length 4 from v1 to v6
There are 17 paths of length 5 from v1 to v6
There are 84 paths of length 6 from v1 to v6


There are 0 paths of length 1 from v1 to v6
There are 1 paths of length 2 from v1 to v6
There are 0 paths of length 3 from v1 to v6
There are 2 paths of length 4 from v1 to v6
There are 0 paths of length 5 from v1 to v6
There are 4 paths of length 6 from v1 to v6


There are 0 paths of length 1 from v1 to v6
There are 4 paths of length 2 fro